# System part
os:
  - linux
sudo: required

# Java specific
language: java
jdk:
  - openjdk8

# Installation
before_install:
  sudo apt-get install gcc g++ swig

install: ./gradlew b

# Gradle specific
cache:
  directories:
  - $HOME/.gradle
